apiVersion: v1
kind: Service
metadata:
 name: nginx-np
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    component: frontend
    purpose: node-port
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80